import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import Main from "./main/Main";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  const { children } = props;

  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Main children={children} />
      </body>
    </html>
  );
}
